### ISSUE TITLE
README examples fail to run

### ISSUE THREAD

**Issue by rkatriel** [explosion/spacy-llm#289]
Hi,

Both examples in the README file fail to run. I get the following error:

ImportError: cannot import name 'SimpleFrozenDict' from 'confection' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py)

It happens when the following is executed (see the full stack trace below):

from spacy_llm.util import assemble

The code is run from within PyCharm on a MacBook Pro (Intel core i7) under macOS Monterey (Version 12.5.1).

Thanks,
Ron

/Library/Frameworks/Python.framework/Versions/3.10/bin/python /Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py 
2023-09-08 10:55:19.576814: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py", line 1, in <module>
    from spacy_llm.util import assemble
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/__init__.py", line 1, in <module>
    from . import cache  # noqa: F401
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/cache.py", line 11, in <module>
    from .ty import LLMTask, PromptTemplateProvider
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/ty.py", line 14, in <module>
    from .models import langchain
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/__init__.py", line 1, in <module>
    from .hf import dolly_hf, openllama_hf, stablelm_hf
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/hf/__init__.py", line 2, in <module>
    from .dolly import dolly_hf
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/hf/dolly.py", line 3, in <module>
    from confection import SimpleFrozenDict
ImportError: cannot import name 'SimpleFrozenDict' from 'confection' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py)

**Comment by svlandeg** [comment]
Hi, thanks for the report!

I wonder whether this is because `SimpleFrozenDict` isn't part of the `__all__` declaration in https://github.com/explosion/confection/blob/main/confection/__init__.py. It ran for us locally and on the CI though. We'll look into it.

Just to double check: which version of `confection` do you have installed?

**Comment by rkatriel** [comment]
Hi Sofie, thanks for the quick reply!

I had confection 0.0.4. I upgraded to 0.1.2 and that solved the error, but now I'm getting a new one:

ValueError: The specified model 'gpt-4' is not availableValueError: The specified model 'gpt-4' is not available

See the full stack trace below.

Best,
Ron

/Library/Frameworks/Python.framework/Versions/3.10/bin/python /Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py 
2023-09-08 11:29:08.348957: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py", line 3, in <module>
    nlp = assemble("config.cfg")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/util.py", line 48, in assemble
    return assemble_from_config(config)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/util.py", line 28, in assemble_from_config
    nlp = load_model_from_config(config, auto_fill=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/util.py", line 564, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/language.py", line 1803, in from_config
    nlp.add_pipe(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/language.py", line 786, in add_pipe
    pipe_component = self.create_pipe(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/language.py", line 679, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py", line 756, in resolve
    resolved, _ = cls._make(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py", line 805, in _make
    filled, _, resolved = cls._fill(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py", line 860, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/confection/__init__.py", line 877, in _fill
    getter_result = getter(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/openai/registry.py", line 43, in openai_gpt_4_v2
    return OpenAI(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/base.py", line 65, in __init__
    self._verify_auth()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/openai/model.py", line 73, in _verify_auth
    raise ValueError(
ValueError: The specified model 'gpt-4' is not available. Choices are: ['ada', 'ada-code-search-code', 'ada-code-search-text', 'ada-search-document', 'ada-search-query', 'ada-similarity', 'babbage', 'babbage-002', 'babbage-code-search-code', 'babbage-code-search-text', 'babbage-search-document', 'babbage-search-query', 'babbage-similarity', 'code-davinci-edit-001', 'code-search-ada-code-001', 'code-search-ada-text-001', 'code-search-babbage-code-001', 'code-search-babbage-text-001', 'curie', 'curie-instruct-beta', 'curie-search-document', 'curie-search-query', 'curie-similarity', 'davinci', 'davinci-002', 'davinci-instruct-beta', 'davinci-search-document', 'davinci-search-query', 'davinci-similarity', 'gpt-3.5-turbo', 'gpt-3.5-turbo-0301', 'gpt-3.5-turbo-0613', 'gpt-3.5-turbo-16k', 'gpt-3.5-turbo-16k-0613', 'text-ada-001', 'text-babbage-001', 'text-curie-001', 'text-davinci-001', 'text-davinci-002', 'text-davinci-003', 'text-davinci-edit-001', 'text-embedding-ada-002', 'text-search-ada-doc-001', 'text-search-ada-query-001', 'text-search-babbage-doc-001', 'text-search-babbage-query-001', 'text-search-curie-doc-001', 'text-search-curie-query-001', 'text-search-davinci-doc-001', 'text-search-davinci-query-001', 'text-similarity-ada-001', 'text-similarity-babbage-001', 'text-similarity-curie-001', 'text-similarity-davinci-001', 'whisper-1']

Process finished with exit code 1

**Comment by svlandeg** [comment]
Happy to hear the issue with `confection` is resolved! We'll make sure to adjust the lower pin so others don't get bitten by this, too. I also released a new version `0.1.3` of `confection` that properly exports the frozen structures as part of the `__all__` in the main module, just in case.

**Comment by svlandeg** [comment]
For this new issue, can you copy paste the config file you're using? This is with a freshly installed `spacy-llm` 0.5.0? Can you try a different model, e.g. 
```
    [components.llm.model]
    @llm_models = "spacy.GPT-3-5.v2"
```
and let us know if that does work?

**Comment by rkatriel** [comment]
I'm using the config file from the README. Here it is, updated as you suggested

```
[nlp]
lang = "en"
pipeline = ["llm"]

[components]

[components.llm]
factory = "llm"

[components.llm.task]
@llm_tasks = "spacy.TextCat.v3"
labels = ["COMPLIMENT", "INSULT"]

[components.llm.model]
@llm_models = "spacy.GPT-3-5.v2"
```

Now I'm getting a different error (see the full stack trace below):

ConnectionError: API could not be reached after 31.684 seconds in total and attempting to connect 5 times. Check your network connection and the API's availability.
429	Too Many Requests

Looks like a server is being overloaded with requests.

Ron

/Library/Frameworks/Python.framework/Versions/3.10/bin/python /Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py 
2023-09-08 11:55:33.184692: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/Users/ron.katriel/PycharmProjects/Transformer/spacy-llm-test.py", line 4, in <module>
    doc = nlp("You look gorgeous!")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/language.py", line 1016, in __call__
    error_handler(name, proc, [doc], e)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/util.py", line 1689, in raise_error
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy/language.py", line 1011, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))  # type: ignore[call-arg]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/pipeline/llm.py", line 156, in __call__
    docs = self._process_docs([doc])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/pipeline/llm.py", line 210, in _process_docs
    responses_iters = tee(self._model(prompts_iters[0]), n_iters)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/openai/model.py", line 115, in __call__
    responses = _request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/openai/model.py", line 86, in _request
    r = self.retry(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/spacy_llm/models/rest/base.py", line 147, in retry
    raise ConnectionError(
ConnectionError: API could not be reached after 31.684 seconds in total and attempting to connect 5 times. Check your network connection and the API's availability.
429	Too Many Requests

Process finished with exit code 1

**Comment by arnomoonens** [comment]
Could be the same problem as I have (no credits on my OpenAI account). See #286

**Comment by rkatriel** [comment]
I believe you are right. This should probably be mentioned upfront in the README.

Does spacy_llm work with any models that don't require a payed OpenAI account?

**Comment by svlandeg** [comment]
@rkatriel : if you want to use a model from OpenAI, we do assume that you have your API key set as environment key, as explained in the first sentences of the [quickstart](https://github.com/explosion/spacy-llm#-quickstart) and with a reference to more info over at the [API docs](https://spacy.io/api/large-language-models#api-keys). If you see any ways of clarifying that further, feel free to submit a pull request :-)

With respect to issue #286 - we'll definitely have a look to ensure that error messages are not getting further confused.

> Does spacy_llm work with any models that don't require a payed OpenAI account?
Yes, you can use an open-source model through Huggingface. Note that you'll need sufficient memory and GPU power on your system to be able to run one. You can have a look at this specific [example](https://spacy.io/usage/large-language-models#example-2) and the [API docs](https://spacy.io/api/large-language-models#models-hf).

**Comment by rkatriel** [comment]
I stand corrected, should have read that section more carefully. Thanks for the pointer to the example using Huggingface! I will try it.

One last question. The default config has the following parameters:

```
[components.llm.task]
@llm_tasks = "spacy.NER.v3"
labels = ["PERSON", "ORGANISATION", "LOCATION"]
```

Does spacy have NER models that are optimized for a healthcare/clinical domain, with labels such as "DISEASE", "PROCEDURE", "DRUG", etc?

**Comment by rmitsch** [comment]
> All (except Llama) installed successfully, but each fails on a different error when running the README example.

Please include in the error messages here.
