### ISSUE TITLE
Spacy-llm bedrock issue

### ISSUE THREAD

**Issue by NaveenKumarStark** [explosion/spacy-llm#372]
I am getting the below error 
```
[2023-11-16 17:39:57,111] ERROR in app: Exception on /watsonnlu [POST]
Traceback (most recent call last):
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nlu_service.py", line 62, in message
    resp = predict(data["input"], data["bot_id"])
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nlu/assistant_nlu.py", line 250, in predict
    intent_result=predict_intent(bot_id,user_query,sql_connection,language,session,Is_FAQ_present)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nlu/predict_intent.py", line 498, in predict_intent
    spacy_llm_output_list=predict_spacy_llm(user_query,file_name)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nlu/predict_intent.py", line 349, in predict_spacy_llm
    Spacy_LLM_model = assemble(config_file_path)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy_llm/util.py", line 48, in assemble
    return assemble_from_config(config)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy_llm/util.py", line 28, in assemble_from_config
    nlp = load_model_from_config(config, auto_fill=True)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy/util.py", line 587, in load_model_from_config
    nlp = lang_cls.from_config(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy/language.py", line 1847, in from_config
    nlp.add_pipe(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy/language.py", line 814, in add_pipe
    pipe_component = self.create_pipe(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy/language.py", line 702, in create_pipe
    resolved = registry.resolve(cfg, validate=validate)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/confection/__init__.py", line 756, in resolve
    resolved, _ = cls._make(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/confection/__init__.py", line 805, in _make
    filled, _, resolved = cls._fill(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/confection/__init__.py", line 860, in _fill
    filled[key], validation[v_key], final[key] = cls._fill(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/confection/__init__.py", line 877, in _fill
    getter_result = getter(*args, **kwargs)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy_llm/models/langchain/model.py", line 90, in langchain_model
    return LangChain(
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/spacy_llm/models/langchain/model.py", line 34, in __init__
    self._langchain_model = LangChain.get_type_to_cls_dict()[api](
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/langchain/load/serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "/Users/Naveen/04102023/assistant_nlu_service_proprietary/nav-spacy-test/lib/python3.9/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Bedrock
model_name
  extra fields not permitted (type=value_error.extra)
```

where my config file is as follows,

```ini
[nlp]
lang = "en"
pipeline = ["llm"]
batch_size = 128

[components]

[components.llm]
factory = "llm"

[components.llm.model]
@llm_models = "langchain.Bedrock.v1"
name = "amazon.titan-text-express-v1"
config = {"model_id": "amazon.titan-text-express-v1"}

[components.llm.task]
@llm_tasks = "spacy.TextCat.v2"
labels = What_can_you_do, Unlock_Account, More_questions
exclusive_classes = false

[components.llm.task.examples]
@misc = "spacy.FewShotReader.v1"
path = "models/nav_testing_3fed4208-dad-4635-8419-b4kumar002_selective_examples.jsonl"

[components.llm.task.normalizer]
@misc = "spacy.LowercaseNormalizer.v1"
```

**Comment by rmitsch** [comment]
Hi @NaveenKumarStark, please always format your code and console output. Thanks for bringing this up, `langchain` seems to expect different keyword args for Bedrock than for other models. We'll patch this up shortly.
