### ISSUE TITLE
ModuleNotFoundError: No module named 'spacy.language'; 'spacy' is not a package

### ISSUE THREAD

**Issue by nxitik** [explosion/spacy-llm#391]
Traceback (most recent call last):
  File "/home/ec2-user/spacy/spacy.py", line 8, in <module>
    from spacy_llm.util import assemble
  File "/home/ec2-user/.conda/envs/naitik2/lib/python3.10/site-packages/spacy_llm/__init__.py", line 1, in <module>
    from . import cache  # noqa: F401
  File "/home/ec2-user/.conda/envs/naitik2/lib/python3.10/site-packages/spacy_llm/cache.py", line 7, in <module>
    from spacy.tokens import Doc, DocBin
  File "/home/ec2-user/spacy/spacy.py", line 8, in <module>
    from spacy_llm.util import assemble
  File "/home/ec2-user/.conda/envs/naitik2/lib/python3.10/site-packages/spacy_llm/util.py", line 5, in <module>
    from spacy.language import Language
ModuleNotFoundError: No module named 'spacy.language'; 'spacy' is not a package

What could be the issue? I am able to use it on Google colab

**Comment by adrianeboyd** [comment]
Rename your script `spacy.py` to a name that doesn't conflict with any module names.

Python appears to be trying to import your `spacy.py` file as the `spacy` module (since local modules have priority for python imports).
